apiVersion: apps/v1
kind: Deployment
metadata:
  name: toy-server-deployment1
spec:
  replicas: 3
  # .spec.minReadySeconds is an optional field that specifies the minimum number
  # of seconds for which a newly created Pod should be ready without any of its
  # containers crashing, for it to be considered available.
  # https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#min-ready-seconds
  minReadySeconds: 10
  strategy:
    rollingUpdate:
        maxUnavailable: 10
        maxSurge: 10
  selector:
    matchLabels:
      manager: toy-server-deployment1
      app: webserver
  template: # pod template
    metadata:
      labels:
        manager: toy-server-deployment1
        app: webserver
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: nginx
        image: nginx:1.14
        ports:
        - name: nginx
          containerPort: 80
      - name: toy-server
        image: mejibyte/toy-server:stable
        imagePullPolicy: Always
        ports:
        - name: webapp
          containerPort: 3000
        env:
          - name: USERNAME
            value: mejibyte
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                  fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                  fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                  fieldPath: spec.serviceAccountName