apiVersion: apps/v1
kind: Deployment
metadata:
  name: toy-server-deployment1
spec:
  replicas: 3
  selector:
    matchLabels:
      manager: toy-server-deployment1
  template:
    metadata:
      labels:
        manager: toy-server-deployment1
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 8080
      - name: toy-server
        image: mejibyte/toy-server:stable
        ports:
        - containerPort: 80
