apiVersion: v1
kind: Service
metadata:
  name: statefulset1-service
  labels:
    mejibyte-experiment: statefulset1
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    mejibyte-experiment: statefulset1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-stateful-app
spec:
  selector:
    matchLabels:
      mejibyte-experiment: statefulset1 # has to match .spec.template.metadata.labels
  serviceName: statefulset1-service
  replicas: 6
  template:
    metadata:
      labels:
        mejibyte-experiment: statefulset1 # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10 # recommended to always have this set for StatefulSet: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#deployment-and-scaling-guarantees
      containers:
      - name: nginx
        # Both images are the same but since the URL is different I can fool k8s into doing a full rolling update.
        image: gcr.io/google_containers/nginx-slim:0.8
        # image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard # The "standard" storage class is automatically configured in minikube and just works
      resources:
        requests:
          storage: 1Gi
